sudo: required

services:
  - docker

script:
  - |
    export VERSION=$(basename $TRAVIS_BRANCH) &&
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker build -t cusspvz/node:${VERSION} . &&

    docker run -ti --rm cusspvz/node:${VERSION} ping &&

    docker build -t cusspvz/node:${VERSION}-onbuild -f Dockerfile.onbuild . &&
    docker build -t cusspvz/node:${VERSION}-development -f Dockerfile.development . &&

    docker push cusspvz/node:${VERSION} &&
    docker push cusspvz/node:${VERSION}-onbuild &&
    docker push cusspvz/node:${VERSION}-development &&
    exit 0 || exit 1
